### ISSUE TITLE
help setting up for home assistant.

### ISSUE THREAD

**Issue by magnetus26** [ClassicDIY/ClassicMQTT#38]
hello,
this is a really interesting project. I was wondering if it can be integrated to home assistant. I do have an esp32 wemos d1 mini. does this board works? 
im really green will need help with hardware and software setup. idk id mosquitto broker will work and i have never used before. 
any help will be mos appreciated
thanks
M.

**Comment by graham22** [comment]
There is some info in the [wiki](https://github.com/ClassicDIY/ClassicMQTT/wiki/6.-Home-Assistant) 
The ESP32 should work.
I use mosquitto running on a Raspberry Pi4, you can use tools like mqtt.fx or mqttExplorer to see the messages being published etc.

**Comment by magnetus26** [comment]
I have read the wiki but cant find anything on how to connect the esp32 to the midnite classic. 
is it there a schematic or diagram on how to do this?
thanks
M.

**Comment by mcsarge** [comment]
The Classic need to be connected to a network using Ethernet and the esp32 needs WiFi. You need an Access Point with that allows your Classic to communicate with the esp32.
