### ISSUE TITLE
Palo mqtt

### ISSUE THREAD

**Issue by wschroed1** [ClassicDIY/ClassicMQTT#43]
It looks like the new version of paho breaks the classic script. I resolved by changing line 480:
#mqttClient = mqttclient.Client(clientId)
    mqttClient = mqttclient.Client(mqttclient.CallbackAPIVersion.VERSION1, clientId)

**Comment by graham22** [comment]
Thanks for your work on this issue,
Updated Classic_mqtt.py and Dockerfile
